import { GlobalLinearProgress, Header, StoreProvider } from "@/shared/ui"
import { ErrorAlert } from "@/shared/ui/ErrorAlert/ErrorAlert"
import '@/shared/styles/global/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true">
        <StoreProvider>
          <Header />
          <div className="scroll-container">
            <main className="content">{children}</main>
          </div>
          <ErrorAlert />
        </StoreProvider>
      </body>
    </html>
  )
}
