import type { Metadata } from 'next'
import '@/shared/styles/global/globals.css'
import { Header } from '@/shared/ui/header/Header'
import { StoreProvider } from '@/shared/ui/StoreProvider/StoreProvider'
import { ReactNode } from 'react'
import Menu from '@/shared/ui/Menu/Menu'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      <body style={{display: 'flex', flexDirection: 'row', justifyContent: 'space-around'}} cz-shortcut-listen="true">
        <StoreProvider>
          <Header />
          <Menu />
          <div className="scroll-container">
            <main className="content">{children}</main>
          </div>
        </StoreProvider>
      </body>
    </html>
  )
}
