import type { Metadata } from 'next'
import '@/shared/styles/global/globals.css'
import { Header } from '@/shared/ui/header/Header'
import { StoreProvider } from '@/shared/ui/StoreProvider/StoreProvider'
import { ReactNode } from 'react'
import { ErrorAlert } from '@/shared/ui/ErrorAlert/ErrorAlert'
import { GlobalLinearProgress } from '@/shared/ui/GlobalLinearProgress/GlobalLinearProgress'
import { Menu } from '@/shared/ui'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en">
      {/*style не нужен*/}
      <body cz-shortcut-listen="true">
        <StoreProvider>
          <Header />
          <div className="scroll-container">
            <GlobalLinearProgress />
            <Menu />
            <main className="content">{children}</main>
          </div>
          <ErrorAlert />
        </StoreProvider>
      </body>
    </html>
  )
}
